// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0BWp1AfYys2THp5Wl7_Dop2a0fu4Qewo',
    appId: '1:718558944860:web:a6b073d82d6f4c4b6c5099',
    messagingSenderId: '718558944860',
    projectId: 'instagram-clone-c75db',
    authDomain: 'instagram-clone-c75db.firebaseapp.com',
    storageBucket: 'instagram-clone-c75db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClv6ZeJZte2kJyeZZawyDVePalUTlivZc',
    appId: '1:718558944860:android:779e6230865d70ce6c5099',
    messagingSenderId: '718558944860',
    projectId: 'instagram-clone-c75db',
    storageBucket: 'instagram-clone-c75db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6TE_sUoM7qgqw2gLW_32zPFj9hZ70XNM',
    appId: '1:718558944860:ios:ef18afb0a4fad1776c5099',
    messagingSenderId: '718558944860',
    projectId: 'instagram-clone-c75db',
    storageBucket: 'instagram-clone-c75db.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6TE_sUoM7qgqw2gLW_32zPFj9hZ70XNM',
    appId: '1:718558944860:ios:f37084d66d690f436c5099',
    messagingSenderId: '718558944860',
    projectId: 'instagram-clone-c75db',
    storageBucket: 'instagram-clone-c75db.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
